### ISSUE TITLE
Rename 'Articles' into something else

### ISSUE THREAD

**Issue by julien-deramond** [Open-reSource/openresource.dev#15]
### Prerequisites

- [X] I have [searched](https://github.com/Open-reSource/openresource.dev/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Open-reSource/openresource.dev/blob/main/CONTRIBUTING.md)

### Proposal

The idea here would be to find a new name for our articles that are not really articles.
I see them atm more like zooms or focuses that could be linked within the guide to go more in-depth into the topic, and its modules/chapters.

### Motivation and context

Better clarity and readability for readers.

**Comment by l2eza** [comment]
@julien-deramond  If you need help in this one, I will be able to help.  🙌
